import type { ProviderAuthField, ProviderModel } from '@/shared/rpc'

/**
 * Built-in provider presets converted from cc-switch claudeProviderPresets.
 * Keep only providers that natively pass through Anthropic requests; exclude:
 * - Official presets without ANTHROPIC_BASE_URL (such as Claude Official with an empty env)
 * - OAuth providers (requiresOAuth / providerType = github_copilot | codex_oauth | xai_oauth)
 * - Non-Anthropic formats (apiFormat = openai_chat | openai_responses | gemini_native)
 * - AWS Bedrock (SigV4 auth and regional templates are incompatible with claudesk's auth model)
 * baseURL and models come from each provider's public Claude-compatible endpoint and are only a starting point.
 * Strip query parameters from websiteUrl to remove affiliate codes.
 */
export type ProviderPreset = {
  id: string
  name: string
  baseURL: string
  authField: ProviderAuthField
  websiteUrl?: string
  /** Override the exact models endpoint used when fetching models. */
  modelsUrl?: string
  models: ProviderModel[]
}

const PROVIDER_NAME_COLLATOR = new Intl.Collator('en', { sensitivity: 'base' })

export const providerPresets: ProviderPreset[] = [
  // ===== Official China providers (cn_official) =====
  {
    id: 'kimi',
    name: 'Kimi',
    baseURL: 'https://api.moonshot.cn/anthropic',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://platform.kimi.com',
    models: [{ id: 'kimi-k2.7-code', displayName: 'Kimi K2.7 Code', contextWindow: 200000 }],
  },
  {
    id: 'kimi-for-coding',
    name: 'Kimi For Coding',
    baseURL: 'https://api.kimi.com/coding/',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://www.kimi.com/code/',
    models: [{ id: 'kimi-for-coding', displayName: 'Kimi For Coding', contextWindow: 262144 }],
  },
  {
    id: 'volcengine-agentplan',
    name: 'Volcengine Agentplan',
    baseURL: 'https://ark.cn-beijing.volces.com/api/coding',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://www.volcengine.com/activity/codingplan',
    models: [{ id: 'ark-code-latest', displayName: 'Ark Code Latest', contextWindow: 200000 }],
  },
  {
    id: 'byteplus',
    name: 'BytePlus',
    baseURL: 'https://ark.ap-southeast.bytepluses.com/api/coding',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://www.byteplus.com/en/product/modelark',
    models: [{ id: 'ark-code-latest', displayName: 'Ark Code Latest', contextWindow: 200000 }],
  },
  {
    id: 'doubao-seed',
    name: 'DouBaoSeed',
    baseURL: 'https://ark.cn-beijing.volces.com/api/compatible',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey',
    models: [
      {
        id: 'doubao-seed-2-1-pro-260628',
        displayName: 'Doubao Seed 2.1 Pro',
        contextWindow: 200000,
      },
    ],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    baseURL: 'https://api.deepseek.com/anthropic',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://platform.deepseek.com',
    modelsUrl: 'https://api.deepseek.com/models',
    models: [
      { id: 'deepseek-v4-pro', displayName: 'DeepSeek V4 Pro', contextWindow: 200000 },
      { id: 'deepseek-v4-flash', displayName: 'DeepSeek V4 Flash', contextWindow: 200000 },
    ],
  },
  {
    id: 'zhipu-glm',
    name: 'Zhipu GLM',
    baseURL: 'https://open.bigmodel.cn/api/anthropic',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://open.bigmodel.cn',
    models: [{ id: 'glm-5.2[1M]', displayName: 'GLM-5.2 1M', contextWindow: 200000 }],
  },
  {
    id: 'zhipu-glm-en',
    name: 'Zhipu GLM en',
    baseURL: 'https://api.z.ai/api/anthropic',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://z.ai',
    models: [{ id: 'glm-5.1', displayName: 'GLM-5.1', contextWindow: 200000 }],
  },
  {
    id: 'baidu-qianfan-coding-plan',
    name: 'Baidu Qianfan Coding Plan',
    baseURL: 'https://qianfan.baidubce.com/anthropic/coding',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://cloud.baidu.com/product/qianfan_modelbuilder',
    models: [
      { id: 'qianfan-code-latest', displayName: 'Qianfan Code Latest', contextWindow: 200000 },
    ],
  },
  {
    id: 'bailian',
    name: 'Bailian',
    baseURL: 'https://dashscope.aliyuncs.com/apps/anthropic',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://bailian.console.aliyun.com',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'bailian-for-coding',
    name: 'Bailian For Coding',
    baseURL: 'https://coding.dashscope.aliyuncs.com/apps/anthropic',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://bailian.console.aliyun.com',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'stepfun',
    name: 'StepFun',
    baseURL: 'https://api.stepfun.com/step_plan',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://platform.stepfun.com/step-plan',
    models: [{ id: 'step-3.5-flash-2603', displayName: 'Step 3.5 Flash', contextWindow: 200000 }],
  },
  {
    id: 'stepfun-en',
    name: 'StepFun en',
    baseURL: 'https://api.stepfun.ai/step_plan',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://platform.stepfun.ai/step-plan',
    models: [{ id: 'step-3.5-flash-2603', displayName: 'Step 3.5 Flash', contextWindow: 200000 }],
  },
  {
    id: 'longcat',
    name: 'Longcat',
    baseURL: 'https://api.longcat.chat/anthropic',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://longcat.chat/platform',
    models: [{ id: 'LongCat-2.0', displayName: 'LongCat 2.0', contextWindow: 200000 }],
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    baseURL: 'https://api.minimaxi.com/anthropic',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://platform.minimaxi.com',
    models: [{ id: 'MiniMax-M2.7', displayName: 'MiniMax M2.7', contextWindow: 200000 }],
  },
  {
    id: 'minimax-en',
    name: 'MiniMax en',
    baseURL: 'https://api.minimax.io/anthropic',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://platform.minimax.io',
    models: [{ id: 'MiniMax-M2.7', displayName: 'MiniMax M2.7', contextWindow: 200000 }],
  },
  {
    id: 'bailing',
    name: 'BaiLing',
    baseURL: 'https://api.tbox.cn/api/anthropic',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://alipaytbox.yuque.com/sxs0ba/ling/get_started',
    models: [{ id: 'Ling-2.5-1T', displayName: 'Ling 2.5 1T', contextWindow: 200000 }],
  },
  {
    id: 'xiaomi-mimo',
    name: 'Xiaomi MiMo',
    baseURL: 'https://api.xiaomimimo.com/anthropic',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://platform.xiaomimimo.com',
    models: [{ id: 'mimo-v2.5-pro', displayName: 'MiMo V2.5 Pro', contextWindow: 200000 }],
  },
  {
    id: 'xiaomi-mimo-token-plan-cn',
    name: 'Xiaomi MiMo Token Plan (China)',
    baseURL: 'https://token-plan-cn.xiaomimimo.com/anthropic',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://platform.xiaomimimo.com/#/token-plan',
    models: [{ id: 'mimo-v2.5-pro', displayName: 'MiMo V2.5 Pro', contextWindow: 200000 }],
  },

  // ===== Third-party providers (third_party) =====
  {
    id: 'packycode',
    name: 'PackyCode',
    baseURL: 'https://www.packyapi.com',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://www.packyapi.com',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'apinebula',
    name: 'APINebula',
    baseURL: 'https://apinebula.com',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://apinebula.com',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'aicodemirror',
    name: 'AICodeMirror',
    baseURL: 'https://api.aicodemirror.com/api/claudecode',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://www.aicodemirror.com',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'patewayai',
    name: 'PatewayAI',
    baseURL: 'https://api.pateway.ai',
    authField: 'ANTHROPIC_API_KEY',
    websiteUrl: 'https://pateway.ai',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'aigocode',
    name: 'AIGoCode',
    baseURL: 'https://api.aigocode.com',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://aigocode.com',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'apikey-fun',
    name: 'APIKEY.FUN',
    baseURL: 'https://api.apikey.fun',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://apikey.fun',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'claudecn',
    name: 'ClaudeCN',
    baseURL: 'https://claudecn.top',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://claudecn.top',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'sssaicode',
    name: 'SSSAiCode',
    baseURL: 'https://node-hk.sssaicodeapi.com/api',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://sssaicodeapi.com',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'micu',
    name: 'Micu',
    baseURL: 'https://www.micuapi.ai',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://www.micuapi.ai',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'rightcode',
    name: 'RightCode',
    baseURL: 'https://www.right.codes/claude',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://www.right.codes',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'etok-ai',
    name: 'ETok.ai',
    baseURL: 'https://api.etok.ai',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://etok.ai',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'cubence',
    name: 'Cubence',
    baseURL: 'https://api.cubence.com',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://cubence.com',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'crazyrouter',
    name: 'CrazyRouter',
    baseURL: 'https://cn.crazyrouter.com',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://www.crazyrouter.com',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'sudocode-chat',
    name: 'SudoCode.chat',
    baseURL: 'https://api.sudocode.chat',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://sudocode.chat',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'sudocode-us',
    name: 'SudoCode.us',
    baseURL: 'https://sudocode.us',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://sudocode.us',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'relaxycode',
    name: 'RelaxyCode',
    baseURL: 'https://www.relaxycode.com',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://www.relaxycode.com',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'e-flowcode',
    name: 'E-FlowCode',
    baseURL: 'https://e-flowcode.cc',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://e-flowcode.cc',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },

  // ===== Aggregators (aggregator) =====
  {
    id: 'zetaapi',
    name: 'ZetaAPI',
    baseURL: 'https://api.zetaapi.ai',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://zetaapi.ai',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'fennoai',
    name: 'FennoAI',
    baseURL: 'https://api.fenno.ai',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://api.fenno.ai',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'runapi',
    name: 'RunAPI',
    baseURL: 'https://runapi.co',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://runapi.co',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'unity2-ai',
    name: 'Unity2.ai',
    baseURL: 'https://api.unity2.ai',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://unity2.ai',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'shengsuanyun',
    name: 'Shengsuanyun',
    baseURL: 'https://router.shengsuanyun.com/api',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://www.shengsuanyun.com',
    models: [
      {
        id: 'anthropic/claude-sonnet-5',
        displayName: 'Claude Sonnet 5',
        contextWindow: 200000,
      },
      {
        id: 'anthropic/claude-haiku-4.5',
        displayName: 'Claude Haiku 4.5',
        contextWindow: 200000,
      },
      { id: 'anthropic/claude-opus-4.8', displayName: 'Claude Opus 4.8', contextWindow: 200000 },
    ],
  },
  {
    id: 'subrouter',
    name: 'SubRouter',
    baseURL: 'https://subrouter.ai',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://subrouter.ai',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'claudeapi',
    name: 'ClaudeAPI',
    baseURL: 'https://gw.claudeapi.com',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://claudeapi.com',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'code0',
    name: 'Code0',
    baseURL: 'https://code0.ai',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://code0.ai',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'teamorouter',
    name: 'TeamoRouter',
    baseURL: 'https://api.teamorouter.com',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://teamorouter.com',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow',
    baseURL: 'https://api.siliconflow.cn',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://siliconflow.cn',
    models: [
      {
        id: 'Pro/MiniMaxAI/MiniMax-M2.7',
        displayName: 'MiniMax M2.7',
        contextWindow: 200000,
      },
    ],
  },
  {
    id: 'siliconflow-en',
    name: 'SiliconFlow en',
    baseURL: 'https://api.siliconflow.com',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://siliconflow.com',
    models: [{ id: 'MiniMaxAI/MiniMax-M2.7', displayName: 'MiniMax M2.7', contextWindow: 200000 }],
  },
  {
    id: 'nekocode',
    name: 'NekoCode',
    baseURL: 'https://nekocode.ai',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://nekocode.ai',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'atlascloud',
    name: 'AtlasCloud',
    baseURL: 'https://api.atlascloud.ai',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://www.atlascloud.ai/console/coding-plan',
    models: [{ id: 'zai-org/glm-5.1', displayName: 'GLM-5.1', contextWindow: 200000 }],
  },
  {
    id: 'compshare',
    name: 'Compshare',
    baseURL: 'https://api.modelverse.cn',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://www.compshare.cn',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'compshare-coding-plan',
    name: 'Compshare Coding Plan',
    baseURL: 'https://cp.compshare.cn',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://www.compshare.cn',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'ccsub',
    name: 'CCSub',
    baseURL: 'https://www.ccsub.net',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://www.ccsub.net',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'dmxapi',
    name: 'DMXAPI',
    baseURL: 'https://www.dmxapi.cn',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://www.dmxapi.cn',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'qiniu',
    name: 'Qiniu',
    baseURL: 'https://api.qnaigc.com',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://s.qiniu.com/nMvAvy',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'amux',
    name: 'Amux',
    baseURL: 'https://api.amux.ai',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://amux.ai',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'modelscope',
    name: 'ModelScope',
    baseURL: 'https://api-inference.modelscope.cn',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://modelscope.cn',
    models: [{ id: 'ZhipuAI/GLM-5.1', displayName: 'GLM-5.1', contextWindow: 200000 }],
  },
  {
    id: 'aihubmix',
    name: 'AiHubMix',
    baseURL: 'https://aihubmix.com',
    authField: 'ANTHROPIC_API_KEY',
    websiteUrl: 'https://aihubmix.com',
    models: [{ id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 }],
  },
  {
    id: 'cherryin',
    name: 'CherryIN',
    baseURL: 'https://open.cherryin.net',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://open.cherryin.ai',
    models: [
      {
        id: 'anthropic/claude-sonnet-5',
        displayName: 'Claude Sonnet 5',
        contextWindow: 200000,
      },
      {
        id: 'anthropic/claude-haiku-4.5',
        displayName: 'Claude Haiku 4.5',
        contextWindow: 200000,
      },
      { id: 'anthropic/claude-opus-4.8', displayName: 'Claude Opus 4.8', contextWindow: 200000 },
    ],
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    baseURL: 'https://openrouter.ai/api',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://openrouter.ai',
    models: [
      {
        id: 'anthropic/claude-sonnet-5',
        displayName: 'Claude Sonnet 5',
        contextWindow: 200000,
      },
      {
        id: 'anthropic/claude-haiku-4.5',
        displayName: 'Claude Haiku 4.5',
        contextWindow: 200000,
      },
      { id: 'anthropic/claude-opus-4.8', displayName: 'Claude Opus 4.8', contextWindow: 200000 },
    ],
  },
  {
    id: 'therouter',
    name: 'TheRouter',
    baseURL: 'https://api.therouter.ai',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://therouter.ai',
    models: [
      {
        id: 'anthropic/claude-sonnet-5',
        displayName: 'Claude Sonnet 5',
        contextWindow: 200000,
      },
      {
        id: 'anthropic/claude-haiku-4.5',
        displayName: 'Claude Haiku 4.5',
        contextWindow: 200000,
      },
      { id: 'anthropic/claude-opus-4.8', displayName: 'Claude Opus 4.8', contextWindow: 200000 },
    ],
  },
  {
    id: 'novita-ai',
    name: 'Novita AI',
    baseURL: 'https://api.novita.ai/anthropic',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://novita.ai',
    models: [{ id: 'zai-org/glm-5.1', displayName: 'GLM-5.1', contextWindow: 200000 }],
  },
  {
    id: 'pipellm',
    name: 'PIPELLM',
    baseURL: 'https://cc-api.pipellm.ai',
    authField: 'ANTHROPIC_AUTH_TOKEN',
    websiteUrl: 'https://code.pipellm.ai',
    models: [
      { id: 'claude-opus-4-8', displayName: 'Claude Opus 4.8', contextWindow: 200000 },
      {
        id: 'claude-haiku-4-5-20251001',
        displayName: 'Claude Haiku 4.5',
        contextWindow: 200000,
      },
      { id: 'claude-sonnet-5', displayName: 'Claude Sonnet 5', contextWindow: 200000 },
    ],
  },
]

providerPresets.sort((a, b) => PROVIDER_NAME_COLLATOR.compare(a.name, b.name))
