import type { AppLanguage } from '@/shared/rpc'

export type ApplicationMenuLabels = {
  about: string
  back: string
  chatHistory: string
  close: string
  copy: string
  cut: string
  edit: string
  file: string
  forward: string
  front: string
  help: string
  keyboardShortcuts: string
  minimize: string
  paste: string
  projectSwitcher: string
  quickPanel: string
  quit: string
  redo: string
  selectAll: string
  sentMessages: string
  taskManager: string
  troubleshooting: string
  toggleDevTools: string
  toggleSidebar: string
  undo: string
  view: string
  window: string
  zoom: string
}

const MENU_LABELS = {
  de: {
    about: 'Über Clotho',
    back: 'Zurück',
    chatHistory: 'Unterhaltungsverlauf',
    close: 'Schließen',
    copy: 'Kopieren',
    cut: 'Ausschneiden',
    edit: 'Bearbeiten',
    file: 'Ablage',
    forward: 'Vorwärts',
    front: 'Alle nach vorn bringen',
    help: 'Hilfe',
    keyboardShortcuts: 'Tastaturkurzbefehle',
    minimize: 'Minimieren',
    paste: 'Einfügen',
    projectSwitcher: 'Projekt wechseln',
    quickPanel: 'Schnellauswahl',
    quit: 'Beenden',
    redo: 'Wiederholen',
    selectAll: 'Alles auswählen',
    sentMessages: 'Gesendete Nachrichten',
    taskManager: 'Task-Manager',
    troubleshooting: 'Problembehebung',
    toggleDevTools: 'Entwicklertools umschalten',
    toggleSidebar: 'Seitenleiste umschalten',
    undo: 'Rückgängig',
    view: 'Darstellung',
    window: 'Fenster',
    zoom: 'Zoom',
  },
  en: {
    about: 'About Clotho',
    back: 'Back',
    chatHistory: 'Chat History',
    close: 'Close',
    copy: 'Copy',
    cut: 'Cut',
    edit: 'Edit',
    file: 'File',
    forward: 'Forward',
    front: 'Bring All to Front',
    help: 'Help',
    keyboardShortcuts: 'Keyboard Shortcuts',
    minimize: 'Minimize',
    paste: 'Paste',
    projectSwitcher: 'Switch Project',
    quickPanel: 'Quick Switcher',
    quit: 'Quit',
    redo: 'Redo',
    selectAll: 'Select All',
    sentMessages: 'Sent Messages',
    taskManager: 'Task Manager',
    troubleshooting: 'Troubleshooting',
    toggleDevTools: 'Toggle Developer Tools',
    toggleSidebar: 'Toggle Sidebar',
    undo: 'Undo',
    view: 'View',
    window: 'Window',
    zoom: 'Zoom',
  },
  es: {
    about: 'Acerca de Clotho',
    back: 'Atrás',
    chatHistory: 'Historial de conversaciones',
    close: 'Cerrar',
    copy: 'Copiar',
    cut: 'Cortar',
    edit: 'Editar',
    file: 'Archivo',
    forward: 'Adelante',
    front: 'Traer todo al frente',
    help: 'Ayuda',
    keyboardShortcuts: 'Atajos de teclado',
    minimize: 'Minimizar',
    paste: 'Pegar',
    projectSwitcher: 'Cambiar de proyecto',
    quickPanel: 'Selector rápido',
    quit: 'Salir',
    redo: 'Rehacer',
    selectAll: 'Seleccionar todo',
    sentMessages: 'Mensajes enviados',
    taskManager: 'Administrador de tareas',
    troubleshooting: 'Solución de problemas',
    toggleDevTools: 'Alternar herramientas de desarrollo',
    toggleSidebar: 'Alternar barra lateral',
    undo: 'Deshacer',
    view: 'Ver',
    window: 'Ventana',
    zoom: 'Zoom',
  },
  fr: {
    about: 'À propos de Clotho',
    back: 'Retour',
    chatHistory: 'Historique des conversations',
    close: 'Fermer',
    copy: 'Copier',
    cut: 'Couper',
    edit: 'Édition',
    file: 'Fichier',
    forward: 'Suivant',
    front: 'Tout ramener au premier plan',
    help: 'Aide',
    keyboardShortcuts: 'Raccourcis clavier',
    minimize: 'Réduire',
    paste: 'Coller',
    projectSwitcher: 'Changer de projet',
    quickPanel: 'Sélecteur rapide',
    quit: 'Quitter',
    redo: 'Rétablir',
    selectAll: 'Tout sélectionner',
    sentMessages: 'Messages envoyés',
    taskManager: 'Gestionnaire des tâches',
    troubleshooting: 'Dépannage',
    toggleDevTools: 'Outils de développement',
    toggleSidebar: 'Afficher/masquer la barre latérale',
    undo: 'Annuler',
    view: 'Affichage',
    window: 'Fenêtre',
    zoom: 'Zoom',
  },
  hi: {
    about: 'Clotho के बारे में',
    back: 'वापस',
    chatHistory: 'बातचीत इतिहास',
    close: 'बंद करें',
    copy: 'कॉपी करें',
    cut: 'काटें',
    edit: 'संपादित करें',
    file: 'फ़ाइल',
    forward: 'आगे',
    front: 'सभी को आगे लाएँ',
    help: 'सहायता',
    keyboardShortcuts: 'कीबोर्ड शॉर्टकट',
    minimize: 'छोटा करें',
    paste: 'पेस्ट करें',
    projectSwitcher: 'प्रोजेक्ट बदलें',
    quickPanel: 'त्वरित स्विचर',
    quit: 'बाहर निकलें',
    redo: 'फिर से करें',
    selectAll: 'सभी चुनें',
    sentMessages: 'भेजे गए संदेश',
    taskManager: 'टास्क मैनेजर',
    troubleshooting: 'समस्या निवारण',
    toggleDevTools: 'डेवलपर टूल टॉगल करें',
    toggleSidebar: 'साइडबार टॉगल करें',
    undo: 'पूर्ववत करें',
    view: 'देखें',
    window: 'विंडो',
    zoom: 'ज़ूम',
  },
  id: {
    about: 'Tentang Clotho',
    back: 'Kembali',
    chatHistory: 'Riwayat percakapan',
    close: 'Tutup',
    copy: 'Salin',
    cut: 'Potong',
    edit: 'Edit',
    file: 'Berkas',
    forward: 'Maju',
    front: 'Bawa Semua ke Depan',
    help: 'Bantuan',
    keyboardShortcuts: 'Pintasan papan tik',
    minimize: 'Minimalkan',
    paste: 'Tempel',
    projectSwitcher: 'Ganti proyek',
    quickPanel: 'Pengalih cepat',
    quit: 'Keluar',
    redo: 'Ulangi',
    selectAll: 'Pilih Semua',
    sentMessages: 'Pesan terkirim',
    taskManager: 'Pengelola tugas',
    troubleshooting: 'Pemecahan masalah',
    toggleDevTools: 'Alat Pengembang',
    toggleSidebar: 'Alihkan bilah samping',
    undo: 'Urungkan',
    view: 'Tampilan',
    window: 'Jendela',
    zoom: 'Zoom',
  },
  ja: {
    about: 'Clotho について',
    back: '戻る',
    chatHistory: '会話履歴',
    close: '閉じる',
    copy: 'コピー',
    cut: 'カット',
    edit: '編集',
    file: 'ファイル',
    forward: '進む',
    front: 'すべてを手前に移動',
    help: 'ヘルプ',
    keyboardShortcuts: 'キーボードショートカット',
    minimize: '最小化',
    paste: 'ペースト',
    projectSwitcher: 'プロジェクトを切り替え',
    quickPanel: 'クイックスイッチャー',
    quit: '終了',
    redo: 'やり直す',
    selectAll: 'すべてを選択',
    sentMessages: '送信済みメッセージ',
    taskManager: 'タスクマネージャー',
    troubleshooting: 'トラブルシューティング',
    toggleDevTools: '開発者ツールの切り替え',
    toggleSidebar: 'サイドバーを切り替え',
    undo: '取り消す',
    view: '表示',
    window: 'ウィンドウ',
    zoom: '拡大／縮小',
  },
  ko: {
    about: 'Clotho 정보',
    back: '뒤로',
    chatHistory: '대화 기록',
    close: '닫기',
    copy: '복사',
    cut: '잘라내기',
    edit: '편집',
    file: '파일',
    forward: '앞으로',
    front: '모두 앞으로 가져오기',
    help: '도움말',
    keyboardShortcuts: '키보드 단축키',
    minimize: '최소화',
    paste: '붙여넣기',
    projectSwitcher: '프로젝트 전환',
    quickPanel: '빠른 전환',
    quit: '종료',
    redo: '다시 실행',
    selectAll: '모두 선택',
    sentMessages: '보낸 메시지',
    taskManager: '작업 관리자',
    troubleshooting: '문제 해결',
    toggleDevTools: '개발자 도구 전환',
    toggleSidebar: '사이드바 전환',
    undo: '실행 취소',
    view: '보기',
    window: '윈도우',
    zoom: '확대/축소',
  },
  'pt-BR': {
    about: 'Sobre o Clotho',
    back: 'Voltar',
    chatHistory: 'Histórico de conversas',
    close: 'Fechar',
    copy: 'Copiar',
    cut: 'Recortar',
    edit: 'Editar',
    file: 'Arquivo',
    forward: 'Avançar',
    front: 'Trazer tudo para a frente',
    help: 'Ajuda',
    keyboardShortcuts: 'Atalhos de teclado',
    minimize: 'Minimizar',
    paste: 'Colar',
    projectSwitcher: 'Trocar de projeto',
    quickPanel: 'Seletor rápido',
    quit: 'Sair',
    redo: 'Refazer',
    selectAll: 'Selecionar Tudo',
    sentMessages: 'Mensagens enviadas',
    taskManager: 'Gerenciador de tarefas',
    troubleshooting: 'Solução de problemas',
    toggleDevTools: 'Ferramentas do desenvolvedor',
    toggleSidebar: 'Alternar barra lateral',
    undo: 'Desfazer',
    view: 'Visualizar',
    window: 'Janela',
    zoom: 'Zoom',
  },
  ru: {
    about: 'О Clotho',
    back: 'Назад',
    chatHistory: 'История диалогов',
    close: 'Закрыть',
    copy: 'Копировать',
    cut: 'Вырезать',
    edit: 'Правка',
    file: 'Файл',
    forward: 'Вперёд',
    front: 'Все окна вперед',
    help: 'Справка',
    keyboardShortcuts: 'Сочетания клавиш',
    minimize: 'Свернуть',
    paste: 'Вставить',
    projectSwitcher: 'Переключить проект',
    quickPanel: 'Быстрый переключатель',
    quit: 'Выйти',
    redo: 'Повторить',
    selectAll: 'Выбрать всё',
    sentMessages: 'Отправленные сообщения',
    taskManager: 'Диспетчер задач',
    troubleshooting: 'Устранение неполадок',
    toggleDevTools: 'Инструменты разработчика',
    toggleSidebar: 'Переключить боковую панель',
    undo: 'Отменить',
    view: 'Вид',
    window: 'Окно',
    zoom: 'Масштаб',
  },
  tr: {
    about: 'Clotho Hakkında',
    back: 'Geri',
    chatHistory: 'Konuşma geçmişi',
    close: 'Kapat',
    copy: 'Kopyala',
    cut: 'Kes',
    edit: 'Düzen',
    file: 'Dosya',
    forward: 'İleri',
    front: 'Tümünü öne getir',
    help: 'Yardım',
    keyboardShortcuts: 'Klavye kısayolları',
    minimize: 'Küçült',
    paste: 'Yapıştır',
    projectSwitcher: 'Proje değiştir',
    quickPanel: 'Hızlı değiştirici',
    quit: 'Çıkış',
    redo: 'Yinele',
    selectAll: 'Tümünü Seç',
    sentMessages: 'Gönderilen mesajlar',
    taskManager: 'Görev yöneticisi',
    troubleshooting: 'Sorun giderme',
    toggleDevTools: 'Geliştirici Araçları',
    toggleSidebar: 'Kenar çubuğunu aç/kapat',
    undo: 'Geri Al',
    view: 'Görünüm',
    window: 'Pencere',
    zoom: 'Yakınlaştır',
  },
  vi: {
    about: 'Giới thiệu Clotho',
    back: 'Quay lại',
    chatHistory: 'Lịch sử trò chuyện',
    close: 'Đóng',
    copy: 'Sao chép',
    cut: 'Cắt',
    edit: 'Sửa',
    file: 'Tệp',
    forward: 'Tiến',
    front: 'Đưa tất cả lên trước',
    help: 'Trợ giúp',
    keyboardShortcuts: 'Phím tắt',
    minimize: 'Thu nhỏ',
    paste: 'Dán',
    projectSwitcher: 'Chuyển dự án',
    quickPanel: 'Bộ chuyển nhanh',
    quit: 'Thoát',
    redo: 'Làm lại',
    selectAll: 'Chọn tất cả',
    sentMessages: 'Tin nhắn đã gửi',
    taskManager: 'Trình quản lý tác vụ',
    troubleshooting: 'Khắc phục sự cố',
    toggleDevTools: 'Công cụ dành cho nhà phát triển',
    toggleSidebar: 'Bật/tắt thanh bên',
    undo: 'Hoàn tác',
    view: 'Xem',
    window: 'Cửa sổ',
    zoom: 'Thu phóng',
  },
  'zh-CN': {
    about: '关于 Clotho',
    back: '返回',
    chatHistory: '历史会话',
    close: '关闭',
    copy: '复制',
    cut: '剪切',
    edit: '编辑',
    file: '文件',
    forward: '前进',
    front: '全部置顶',
    help: '帮助',
    keyboardShortcuts: '键盘快捷键',
    minimize: '最小化',
    paste: '粘贴',
    projectSwitcher: '切换项目',
    quickPanel: '快速切换',
    quit: '退出',
    redo: '重做',
    selectAll: '全选',
    sentMessages: '已发送消息',
    taskManager: '任务管理器',
    troubleshooting: '故障排除',
    toggleDevTools: '切换开发者工具',
    toggleSidebar: '切换侧边栏',
    undo: '撤销',
    view: '显示',
    window: '窗口',
    zoom: '缩放',
  },
  'zh-TW': {
    about: '關於 Clotho',
    back: '返回',
    chatHistory: '歷史對話',
    close: '關閉',
    copy: '複製',
    cut: '剪下',
    edit: '編輯',
    file: '檔案',
    forward: '前進',
    front: '全部置於最前',
    help: '說明',
    keyboardShortcuts: '鍵盤快速鍵',
    minimize: '最小化',
    paste: '貼上',
    projectSwitcher: '切換專案',
    quickPanel: '快速切換',
    quit: '結束',
    redo: '重做',
    selectAll: '全選',
    sentMessages: '已傳送訊息',
    taskManager: '工作管理員',
    troubleshooting: '疑難排解',
    toggleDevTools: '切換開發人員工具',
    toggleSidebar: '切換側邊欄',
    undo: '復原',
    view: '顯示',
    window: '視窗',
    zoom: '縮放',
  },
} satisfies Record<AppLanguage, ApplicationMenuLabels>

export function menuLabels(language: AppLanguage): ApplicationMenuLabels {
  return MENU_LABELS[language]
}
