import type { ClaudeJsonLine } from '@/shared/rpc'

export type SessionEntry = ClaudeJsonLine

export type SessionMeta = {
  title: string
  custom_title?: string
  ai_title?: string
  first_prompt?: string
  git_branch?: string
  tag?: string
}

export type HeadTail = {
  head: string
  tail: string
}

export function textFromContent(content: unknown) {
  if (typeof content === 'string') {
    const text = content.trim()
    return text ? text : undefined
  }

  if (!Array.isArray(content)) {
    return undefined
  }

  const text = content
    .map((part) => {
      if (!part || typeof part !== 'object') {
        return ''
      }
      const entry = part as Record<string, unknown>
      if (typeof entry.text === 'string') {
        return entry.text
      }
      if (typeof entry.content === 'string') {
        return entry.content
      }
      return ''
    })
    .filter(Boolean)
    .join('\n')
    .trim()

  return text || undefined
}

function cleanCommandTags(content: string) {
  function extractTag(tag: string) {
    const open = `<${tag}>`
    const close = `</${tag}>`
    const start = content.indexOf(open)
    if (start === -1) {
      return undefined
    }
    const from = start + open.length
    const end = content.indexOf(close, from)
    if (end === -1) {
      return undefined
    }
    const value = content.slice(from, end).trim()
    return value || undefined
  }

  const commandName = extractTag('command-name')
  if (!commandName) {
    return content
  }
  const commandArgs = extractTag('command-args') ?? ''
  return commandArgs ? `${commandName} ${commandArgs}` : commandName
}

function extractValueAt(windowText: string, valueStart: number) {
  const bytes = Array.from(windowText)
  for (let index = valueStart; index < bytes.length; index += 1) {
    if (bytes[index] === '\\') {
      index += 1
      continue
    }
    if (bytes[index] === '"') {
      return unescapeJsonString(windowText.slice(valueStart, index))
    }
  }
  return undefined
}

function unescapeJsonString(raw: string) {
  let out = ''
  for (let index = 0; index < raw.length; index += 1) {
    const value = raw[index]
    if (value !== '\\') {
      out += value
      continue
    }

    index += 1
    const escaped = raw[index]
    switch (escaped) {
      case '"':
      case '\\':
      case '/':
        out += escaped
        break
      case 'n':
        out += '\n'
        break
      case 't':
        out += '\t'
        break
      case 'r':
        out += '\r'
        break
      case 'b':
        out += '\b'
        break
      case 'f':
        out += '\f'
        break
      case 'u': {
        const hex = raw.slice(index + 1, index + 5)
        if (/^[0-9a-fA-F]{4}$/.test(hex)) {
          out += String.fromCodePoint(Number.parseInt(hex, 16))
          index += 4
        }
        break
      }
      default:
        break
    }
  }
  return out
}

export function fieldFirst(windowText: string, key: string) {
  for (const form of [`"${key}":"`, `"${key}": "`]) {
    const index = windowText.indexOf(form)
    if (index === -1) {
      continue
    }
    const value = extractValueAt(windowText, index + form.length)
    if (value !== undefined) {
      return value
    }
  }
  return undefined
}

export function fieldLast(windowText: string, key: string) {
  let best: { position: number; value: string } | undefined

  for (const form of [`"${key}":"`, `"${key}": "`]) {
    let searchFrom = 0
    while (searchFrom < windowText.length) {
      const relative = windowText.slice(searchFrom).indexOf(form)
      if (relative === -1) {
        break
      }
      const position = searchFrom + relative
      const valueStart = position + form.length
      const value = extractValueAt(windowText, valueStart)
      if (value !== undefined && (!best || position > best.position)) {
        best = { position, value }
      }
      searchFrom = valueStart + 1
    }
  }

  return best?.value
}

export function firstUserPrompt(head: string) {
  for (const line of head.split('\n')) {
    if (!line.includes('"type":"user"') && !line.includes('"type": "user"')) {
      continue
    }
    if (
      line.includes('"tool_result"') ||
      line.includes('"isMeta":true') ||
      line.includes('"isMeta": true') ||
      line.includes('"isCompactSummary":true') ||
      line.includes('"isCompactSummary": true')
    ) {
      continue
    }

    try {
      const parsed = JSON.parse(line) as SessionEntry
      const text = textFromContent(parsed.message?.content)
      if (!text) {
        continue
      }
      if (
        text.includes(
          'Caveat: The messages below were generated by the user while running local commands',
        ) ||
        text.startsWith('<local-command-stdout>')
      ) {
        continue
      }
      return cleanCommandTags(text)
    } catch {
      continue
    }
  }

  return undefined
}

export function extractSessionMeta({ head, tail }: HeadTail) {
  const firstLine = head.split('\n')[0] ?? ''
  if (firstLine.includes('"isSidechain":true') || firstLine.includes('"isSidechain": true')) {
    return undefined
  }

  const customTitle = fieldLast(tail, 'customTitle') ?? fieldLast(head, 'customTitle')
  const aiTitle = fieldLast(tail, 'aiTitle') ?? fieldLast(head, 'aiTitle')
  const prompt = firstUserPrompt(head)

  const title =
    customTitle ?? aiTitle ?? fieldLast(tail, 'lastPrompt') ?? fieldLast(tail, 'summary') ?? prompt

  if (!title) {
    return undefined
  }

  const gitBranch = fieldLast(tail, 'gitBranch') ?? fieldFirst(head, 'gitBranch')
  const tag = tail
    .split('\n')
    .reverse()
    .find((line) => line.includes('"type":"tag"') && line.includes('"tag":"'))

  return {
    title,
    custom_title: customTitle,
    ai_title: aiTitle,
    first_prompt: prompt,
    git_branch: gitBranch,
    tag: tag ? fieldLast(tag, 'tag') : undefined,
  } satisfies SessionMeta
}
